version: '2.3'

services:

  conductor-server:
    environment:
      - CONFIG_PROP=config-mysql-grpc.properties
    image: zen369/conductor-server:v3.13.8-optimize
    container_name: conductor-server
    volumes:
      - ./config:/app/config
    build:
      context: ../../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
      - 8090:8090
    links:
      - elasticsearch:es
      - redis:rs
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080
    image: zen369/conductor-ui:v3.13.8-optimize
    container_name: conductor-ui
    build:
      context: ../../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    depends_on:
      - conductor-server
    stdin_open: true

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: Mysql123Conductor
      MYSQL_DATABASE: conductor
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Mysql123Conductor
    volumes:
      - type: volume
        source: conductor_mysql
        target: /var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/3306'
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: redis:6.2.3-alpine
    command: --requirepass Redis123Conductor --appendonly yes
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-conductor:/data
    networks:
      - internal
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  elasticsearch:
    image: elasticsearch:6.8.23
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=ElasticSearch123Conductor
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  esdata-conductor:
    driver: local
  conductor_mysql:
  redis-data-conductor:

networks:
  internal:
